#!/usr/bin/env python
import aiml
import speech_recognition as sr
import voice_engine

# Create the kernel and learn AIML files
kernel = aiml.Kernel()
kernel.learn("std-startup.xml")
kernel.respond("load aiml b")


recognizer = sr.Recognizer()
# Press CTRL-C to break this loop
while True:
    with sr.Microphone() as source:
        print("Say something!")
        audio = recognizer.listen(source)
        text = voice_engine.get_text_from_speech(audio, recognizer)
        text = str(text)
        print(text)
    output = kernel.respond(text)
    print(output)
    voice_engine.get_speech_from_text(output)
   
